const express = require("express")
const router = express.Router() 
const AdminController = require("../controller/adminController") 

router.get("/admin" , AdminController.getAdminLogin) 
router.post('/admin', AdminController.postAdmin)
router.get("/admin/new" , AdminController.getAdminRegister) 
router.post("/admin/new", AdminController.postNewAdmin)
router.get("/admin/dashboard" , AdminController.isLogin, AdminController.getAdminDashboard)
router.get('/admin/logout', AdminController.handleLogout)
router.get("/setup/accounts" , AdminController.getAccountSetup) 
router.post("/setup/accounts" , AdminController.handleCreateAccount) 
router.get("/setup/account-ledger", AdminController.postLedgers)
router.get("/setup/taxes" , AdminController.getTaxSetup) 
router.post("/setup/taxes" , AdminController.handleCreateTax)
router.get("/setup/lgas" , AdminController.getLGASetup)  
router.post("/setup/lgas" , AdminController.handleCreateLGA)  
router.get("/setup/streets" , AdminController.getStreetSetup) 
router.post("/setup/streets" , AdminController.handleCreateStreet) 
router.get("/setup/locations" , AdminController.getLocationSetup) 
router.post("/setup/locations" , AdminController.handleCreateLocation)  
router.get("/setup/payers" , AdminController.getPayerSetup) 
router.post("/setup/payers" , AdminController.handlePayer) 
router.get("/setup/properties" , AdminController.getPropertiesSetup) 
router.post("/setup/properties" , AdminController.createProperty) 
router.get("/setup/penalties" , AdminController.getPenaltiesSetup) 
router.get("/setup/premise" , AdminController.getPremise)   
router.post("/setup/penalties" , AdminController.handlePenalty) 
router.get("/payments" , AdminController.getPaymentPage) 
router.get("/setup/revenue-head" , AdminController.getRevenueHead) 
router.post("/setup/revenue-head" , AdminController.handleRevenueHead) 
router.get("/revenue/charges" , AdminController.getCharges) 
router.post("/revenue/charges" , AdminController.handleCharge) 
router.post("/charge-detail" , AdminController.getChargeDetail) 
// router.post("/make-payment" , AdminController.savePayment)  
router.get("/charge-payee" , AdminController.proceedToPayment) 
router.get("/budgets" , AdminController.getBudgets) 
router.post("/budgets" , AdminController.handleBudget) 
router.get("/budgets/:budgetCode" , AdminController.getSingleBudget) 

module.exports = router 
